services:
  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - /tmp:/tmp
    env_file:
      - .env

networks:
  app-network:
    driver: bridge